### ISSUE TITLE
Serialize of TArray<Byte> is wrong

### ISSUE THREAD

**Issue by chmichael** [grijjy/GrijjyFoundation#35]
Hello.
  using TgoBsonSerializer.Serialize into the following record:
`  
RInfo = record
  Usages: TArray<Byte>;
end;
`

Will serialize into: 
[
    {
        "Usages":{
            "$binary":"DwoRCxANERM=",
            "$type":"00"
        },
    }
]

instead of:
[
    {
        "Usages":[
            11,
            15,
            17,
            5,
            17,
            15,
            28,
            46
        ]
    }
]

if i switch to shortint the result will output correctly.

Thank you

**Comment by mcvanderkooij** [comment]
And what happens if you use:
RInfo = record
Usages: TArray<byte>;
end;

**Comment by chmichael** [comment]
My apologies, it's a typo the correct one is: 

RInfo = record
Usages: TArray<Byte>;
end;

**Comment by erikvanbilsen** [comment]
The way `TArray<Byte>` (or `TBytes`) is serialized isn't wrong but a design decision. Since `TBytes` is usually used to store binary data, it is stored as binary data by default.

You can use the `[BsonRepresentation(...)]` attribute to control how fields should be serialized. For `TBytes`, the options used to be `Binary` (default) and `String` (a hex string). However, I just added the option `Array` to serialize as a regular JSON array.

You can use this attribute like this:

``` Delphi
type
  RInfo = record
    [BsonRepresentation(TgoBsonRepresentation.Array)]
    Usages: TArray<Byte>;
  end;
```

Hope this resolves your issue.

**Comment by chmichael** [comment]
That was fast! Many Thanks!
The problem now is that Deserialize will throw an error if i use the [BsonRepresentation(TgoBsonRepresentation.Array)] on the byte array!

Thank you

**Comment by erikvanbilsen** [comment]
I am not able to reproduce this. Could you reply with a call stack and exact error message? Or otherwise some sample code that shows the issue? Thanks.

**Comment by chmichael** [comment]
It seems my code got a little bit out of sync with shortints and bytes and it was trying to pass negative values to the byte array.
My bad! Thank you again!
