### ISSUE TITLE
TgoBsonSerializer.SerializeDateTime - TgoBsonRepresentation.String (line 2513)

### ISSUE THREAD

**Issue by mitzix** [grijjy/GrijjyFoundation#58]
Your conversion of milliseconds to string is not correct. Consider TDateTime value 45562.3361695139 which is correctly represented as 27.9.2024 08:04:05.046. But your conversion makes string 27.9.2024 08:04:05.460000, which is nonsense as you can see.

You should use either 

S := S + FormatDateTime('"."zzz',AValue);

or microsecond precision

var dt := Frac(AValue); 
dt := dt * 24*60*60; 
var us := IntToStr(Round(Frac(dt)*1000000));
S := S + '.'+ StringOfChar('0', 6-Length(us)) + us;

But there's problem with non-periodic decimal because then you get
27.9.2024 08:04:05.046001

which must not be in all cases correct.

**Comment by mitzix** [comment]
dt := dt * 24 * 60 * 60;

**Comment by erikvanbilsen** [comment]
Since this library is based on the C# MongoDB driver, I followed the same conventions as their library. Their convention for the String representation was to serialize milliseconds in units of ten millionths of a second (using [this](https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#FFFFFFF_Specifier) C# format specifier). I don't know the reasoning behind this.

However, since our documentation says we use the ISO-8601 format for String representations, I changed to code to use this format instead (which matches what you expected).
